version: '3.7'
services:
  database:
    image: mysql:latest 
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
      - ./.docker/mysql/dump:/docker-entrypoint-initdb.d
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: fs
      MYSQL_PASSWORD: fs
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: fastservice
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    depends_on:
      - database